blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/samcogan-demo/.github/discussions
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://github.com/samcogan-demo/.github/wiki
    about: Check our documentation and guides
